var observer = new MutationObserver(function (records) {
	const iframes = document.querySelectorAll("article iframe")
	for (let i = 0; i < iframes.length; i++) {

		iframes[i].addEventListener("load", function (e) {
			//console.log("load iframe", e.target.getAttribute("src"))
			const el = e.target.parentElement
			//console.log(e.timeStamp)

			//if (e.timeStamp < 6000) {
			el.children[0].style.display = "none"
			el.children[1].classList.remove("hidden-iframe")
			//}
			//tester délai avec https://bettycollober.fr/en-ce-moment
		})
	}
})

const main = document.getElementById("main")
observer.observe(main, {
	childList: true,
	characterData: true
})

const sourcesURL = [
	"https://ribambelle.club/~cabanes",
	"https://ribambelle.club/~castor-aimable",
	"https://ribambelle.club/~llaq",
	"https://ribambelle.club/~nouckey",
	"https://ribambelle.club/~boucan",
	"https://ribambelle.club/~slowpy",
	"https://ribambelle.club/~kamouth",
	"https://ribambelle.club/~zoutof",
	"https://accentgrave.net/now/",
	"https://philippe-castelneau.com/en-ce-moment/",
	"https://julianoe.eu.org/en-ce-moment",
	"https://lamecarlate.net/en-ce-moment",
	"https://justman.fr/now",
	"https://tangee.fr/now/",
	"https://www.6x8.org/en-ce-moment",
	"https://nota-bene.org/now",
	"https://themimitoof.fr/now",
	"https://11d.im/now/",
	"https://sima78.chispa.fr…x.php?pages/En-ce-moment",
	"https://villepreux.net/now",
	"https://fourbi.eu/en-ce-moment",
	"https://claudeaubry.fr/now/",
	"https://www.ffoodd.fr/now/",
	"https://timotheejulien.fr/en-ce-moment/",
	"https://cybercarnet.lahm…b.net/index.php?page=now",
	"https://blog.erreur503.xyz/en-ce-moment/",
	"https://kevinronceray.com/now",
	"https://herve.bzh/now/",
	"https://dimitriregnier.net/now",
	"https://louphole.com/a-propos/#now",
	"https://gersande.com/blogue/now/",
	"https://www.pachyderme.net/now",
	"https://timothee.goguely.com/now",
	"https://blog.poslovitch.fr/en-ce-moment",
	"https://julietterobert.com/en-ce-moment",
	"https://bettycollober.fr/en-ce-moment",
	"https://www.couchet.org/#now",
	"https://nico.nacq.me/now",
	"https://omer.mobi/maintenant",
	"https://www.enroweb.com/now.html",
	"https://luce.carevic.eu/fr/now",
	"https://www.nicolas-hoffmann.net/source/now.php",
	"https://hello-bokeh.fr/now",
	"https://www.nicolas-birckel.fr/now/",
	"https://www.atlza.com/now/",
	"https://wiki.xxiivv.com",
	"https://electro.pizza",
	"https://avanier.dev",
	"https://detritus.zone",
	"https://hraew.autophagy.io",
	"https://heracl.es",
	"https://now.lectronice.com",
	"https://craze.co.uk",
	"https://shaneckel.com",
	"https://cblgh.org",
	"https://ellugar.co",
	"https://chigby.org",
	"https://longest.voyage",
	"https://palomakop.tv",
	"https://2d4.dev",
	"https://nathanwentworth.co",
	"https://wasin.io",
	"https://inns.studio",
	"https://kokorobot.ca",
	"https://wake.st",
	"https://bildwissenschaft.vortok.info",
	"https://aeriform.io",
	"https://nonmateria.com",
	"https://drisc.io",
	"https://ricky.codes",
	"https://maxdeviant.com",
	"https://tynandebold.com",
	"https://nomand.co",
	"https://mmm.s-ol.nu",
	"https://smidgeo.com/bots",
	"https://iko.soy",
	"https://ritualdust.com",
	"https://magoz.is",
	"https://szymonkaliski.com",
	"https://rosano.ca",
	"https://yiming.dev/",
	"https://hex22.org",
	"https://patrikarvidsson.com",
	"https://sophieleetmaa.com",
	"https://xinniw.net",
	"https://tom.so",
	"https://www.madewithtea.com",
	"https://buzzert.net",
	"https://serocell.com",
	"https://kor.nz",
	"https://lublin.se",
	"https://zanneth.com",
	"https://eli.li",
	"https://gosha.net",
	"https://azlen.me",
	"https://opguides.info",
	"https://chrismaughan.com/",
	"https://oddworlds.org",
	"https://fundor333.com/",
	"https://cass.si",
	"https://mdbenning.neocities.org/",
	"https://sixey.es/",
	"https://jameschip.io",
	"https://patrick-is.cool",
	"https://crlf.link",
	"https://esi.is",
	"https://rezmason.net",
	"https://estfyr.net",
	"https://natwelch.com",
	"https://0xff.nu",
	"https://sunshinegardens.org/~xj9/",
	"https://q.pfiffer.org/",
	"https://zvava.org",
	"https://amorphic.space",
	"https://www.edwinwenink.xyz",
	"https://copiona.com",
	"https://proycon.anaproy.nl",
	"https://roytang.net",
	"https://dampfkraft.com",
	"https://travisshears.com",
	"https://awalvie.me",
	"https://futuristan.io",
	"https://yctct.com/",
	"https://ix5.org/",
	"https://www.juliendesrosiers.com/",
	"https://nchrs.xyz",
	"https://nor.the-rn.info",
	"https://matildepark.ca",
	"https://deianeira.co",
	"https://inqlab.net",
	"https://abstractxan.xyz",
	"https://mxmarin.ca",
	"https://metasyn.pw",
	"https://www.milofultz.com",
	"https://thomasorus.com",
	"https://notes.neeasade.net/",
	"https://notebook.wesleyac.com",
	"https://wol.fm",
	"https://void.cc",
	"https://hecanjog.com",
	"https://fragmentscenario.com/",
	"https://corvid.cafe/",
	"https://aless.co",
	"https://weakty.com",
	"https://mrshll.com",
	"https://everest-pipkin.com/",
	"https://h.soucy.cc",
	"https://fragments.hew.tt",
	"https://pbat.ch",
	"https://www.gr0k.net",
	"https://clarity.flowers",
	"https://tendigits.space",
	"https://sirtetris.com",
	"https://caffeine.wiki",
	"https://itwont.work",
	"https://badd10de.dev",
	"https://nilfm.cc",
	"https://wilde-at-heart.garden",
	"https://pixouls.xyz",
	"https://embyr.sh",
	"https://www.maxhaesslein.de",
	"https://compudanzas.net",
	"https://yhnck.xyz",
	"https://astrid.tech",
	"https://flower.codes",
	"https://noelle.dev",
	"https://www.giacintocarlucci.it",
	"https://www.paritybit.ca",
	"https://vlad.website",
	"https://plastic-idolatry.com/erik",
	"https://ferale.art",
	"https://toyos.dev/",
	"https://www.wellobserve.com/",
	"https://d00k.net/",
	"https://detondev.com",
	"https://arcades.agency",
	"https://jache.re",
	"https://helveticablanc.com/",
	"https://colindrake.me",
	"https://log.tone.support",
	"https://armaina.com/",
	"https://sindhu.live",
	"https://nuel.pw",
	"https://ffs.fm",
	"https://www.aphrodite.dev/",
	"https://zeal.co",
	"https://nataziel.nexus",
	"https://canalswans.commoninternet.net",
	"https://kira.eight45.net",
	"https://chotrin.org",
	"https://emile.space",
	"https://mayaks.eu",
	"https://vit.baisa.cz",
	"https://jbztl.fr",
	"https://www.kxvin.com",
	"https://nebula.ed1.club/stuff/",
	"https://wiki.plungepool.dev",
	"https://aaronstrick.com",
	"https://ghettobastler.com",
	"https://ayu.land",
	"https://tosatur.com",
	"https://pfy.ch",
	"https://benji.dog",
	"https://wreckage.link",
	"https://h3rald.com",
	"https://luis.zip",
	"https://monoxane.io",
	"https://lndf.fr",
	"https://ratfactor.com",
	"https://hideout.ink",
	"https://wilburzhang.com",
	"https://parth.ninja/",
	"https://malloc.dog",
	"https://shrik3.com",
	"https://jshuang.art",
	"https://zinzy.website",
	"https://mattmcadams.com",
	"https://prin.lu",
	"https://grains.cc",
	"https://proto.garden",
	"https://kjelsrud.dev",
	"https://jaredforth.com",
	"https://aksui.com/",
	"https://femishonuga.com",
	"https://strengthofone.com",
	"https://garden.sunils.in",
	"https://notebook.zoeblade.com",
	"https://lunabee.space/extraspace/port.html",
	"https://jakintosh.com",
	"https://dziban.net",
	"https://www.huotart.com",
	"https://www.drawk.cab/",
	"https://plantay.me",
	"https://alexeystar.com/",
	"https://22h49.one",
	"https://laeastra.com",
	"https://ribo.zone/neighborhood",
	"https://visualculture.vc",
	"https://leetusman.com",
	"https://arne.xyz",
	"https://triapul.cz/",
	"https://churchbasement.org/",
	"https://sebastian.graphics/",
	"https://adamledoux.net",
	"https://comma.directory/",
	"https://meirisoda.online",
	"https://kelp.lt/",
	"https://ewen.io/",
	"https://satyarth.me/",
	"https://anders.conbere.org",
	"https://monolyt.co",
	"https://klaxzy.net",
	"https://grtsk.com",
	"https://falai.se",
	"https://sanalog.net/blog",
	"https://aleteoryx.me",
	"https://zewski.net",
	"https://drkhsh.at",
	"https://ivndbt.com/",
	"https://zacharykai.net",
	"https://eevie.dev",
	"https://bugwhisperer.dev",
	"https://akavel.com",
	"https://stage7.net",
	"https://idiomdrottning.org",
	"https://thedaemons.space",
	"https://krzysckh.org",
	"https://dalem.foo",
	"https://rmv.fyi",
	"https://nnix.com",
	"https://blog.darylsun.page",
	"https://www.lazaruscorporation.co.uk",
	"https://tanner.vc",
	"https://lichendust.com",
	"https://si3t.ch",
	"https://angelwood.xyz",
	"https://zhcet.net",
	"https://chris-besch.com",
	"https://rubensabatini.com",
	"https://juliannes.website",
	"https://gregori.studio",
	"https://brennan.day",
	"https://l1zb3th.online",
]


let elements = []
document.addEventListener("DOMContentLoaded", async (e) => {

	const main = document.querySelector("body main")
	for (let index = 0; index < sourcesURL.length; index++) {


		let element = document.createElement("article")
		element.innerHTML = `
	<div class='fallback'>
		<p>🌃</p>
	</div>
	<iframe
			class="hidden-iframe"
			id='${sourcesURL[index]}'
			src='${sourcesURL[index]}'
			loading='lazy'
			scrolling='yes'
			referrerpolicy='no-referrer'>
		</iframe>`
		elements.push(element)

	}
	main?.append(...elements)
})


const dialog = document.querySelector("dialog")
const showButton = document.querySelector("header span")
const closeButton = document.querySelector("dialog button")

// Le bouton "Afficher la fenêtre" ouvre le dialogue
showButton.addEventListener("click", () => {
	dialog.showModal()
})

// Le bouton "Fermer" ferme le dialogue
closeButton.addEventListener("click", () => {
	dialog.close()
})

export { }
