//Sources
// https://ribambelle.club/
// https://encemoment.site/
// https://wiki.xxiivv.com/site/webring.html
export const sourcesURL = [["cabanes", "https://ribambelle.club/~cabanes/"],
["castor-aimable", "https://ribambelle.club/~castor-aimable/"],
["llaq", "https://ribambelle.club/~llaq/"],
["nouckey", "https://ribambelle.club/~nouckey/"],
["boucan", "https://ribambelle.club/~boucan/"],
["slowpy", "https://ribambelle.club/~slowpy/"],
["kamouth", "https://ribambelle.club/~kamouth/"],
["zoutof", "https://ribambelle.club/~zoutof/"],
["Et maintenant ?", "https://accentgrave.net/now/"],
["En ce moment – Philippe Castelneau", "https://philippe-castelneau.com/en-ce-moment/"],
["En ce moment - carnet de notes de Julianoë", "https://julianoe.eu.org/en-ce-moment/"],
["En ce moment — lamecarlate.net", "https://lamecarlate.net/en-ce-moment/"],
["En ce moment dans la matrice", "https://justman.fr/now/"],
["En ce moment — Tangee's blog", "https://tangee.fr/now/"],
["En ce moment - 6x8", "https://www.6x8.org/en-ce-moment/"],
["Now | nota-bene.org (le site de stef)", "https://nota-bene.org/now/"],
["Quoi de beau Themimitoof ?", "https://themimitoof.fr/now/"],
["Alors tu fais quoi en ce moment, tk ?", "https://11d.im/now/"],
["Il en est où Sima78 ?", "https://sima78.chispa.fr…x.php?pages/En-ce-moment/"],
["En ce moment — Antoine / La Villa Pirorum", "https://villepreux.net/now/"],
["En ce moment dans le carnet de Joachim", "https://fourbi.eu/en-ce-moment/"],
["Et maintenant - Scrum, Agilité & rock'n roll", "https://claudeaubry.fr/now/"],
["En ce moment chez Gaël — La vie en #ffoodd", "https://www.ffoodd.fr/now/"],
["En ce moment | Timothée JULIEN", "https://timotheejulien.fr/en-ce-moment/"],
["Lahminewski en ce moment ...", "https://cybercarnet.lahm…b.net/index.php?page=now/"],
["En ce moment — Erreur 503", "https://blog.erreur503.xyz/en-ce-moment/"],
["En ce moment • Kévin Ronceray", "https://kevinronceray.com/now/"],
["En ce moment | Jeremy Hervé", "https://herve.bzh/now/"],
["Now | Dimitri Régnier, producteur d'émotions", "https://dimitriregnier.net/now/"],
["En ce moment chez Bilgé Kimyonok", "https://louphole.com/a-propos/#now/"],
["À c't'heure - gersande", "https://gersande.com/blogue/now/"],
["Aziz Paul Ctrian", "https://www.pachyderme.net/now/"],
["En ce moment -  timothee.goguely", "https://timothee.goguely.com/now/"],
["En ce moment — l'Atelier de Poslovitch", "https://blog.poslovitch.fr/en-ce-moment/"],
["En ce moment | Juliette Robert", "https://julietterobert.com/en-ce-moment/"],
["En ce moment - Betty", "https://bettycollober.fr/en-ce-moment/"],
["En ce moment / Frédéric Couchet", "https://www.couchet.org/#now/"],
["Il fait quoi Nico ces temps-ci ?", "https://nico.nacq.me/now/"],
["En ce moment | Omer Pesquer", "https://omer.mobi/maintenant/"],
["Antoine Blanchard | En ce moment", "https://www.enroweb.com/now.html/"],
["En ce moment | Luce Carević", "https://luce.carevic.eu/fr/now/"],
["Il fait quoi au fait Nicolas ?", "https://www.nicolas-hoffmann.net/source/now.php/"],
["En ce moment / Hello Bokeh", "https://hello-bokeh.fr/now/"],
["En ce moment — Nicolas Birckel", "https://www.nicolas-birckel.fr/now/"],
["Quoi de neuf par les temps qui courent ?", "https://www.atlza.com/now/"],
["xxiivv", "https://wiki.xxiivv.com/"],
["electro pizza", "https://electro.pizza/"],
["avanier", "https://avanier.dev/"],
["detritus.zone", "https://detritus.zone/"],
["hraew.autophagy", "https://hraew.autophagy.io/"],
["heracl.es", "https://heracl.es/"],
["lectronice", "https://now.lectronice.com/"],
["craze.co.uk", "https://craze.co.uk/"],
["shaneckel", "https://shaneckel.com/"],
["cblgh", "https://cblgh.org/"],
["ellugar", "https://ellugar.co/"],
["chigby", "https://chigby.org/"],
["longest.voyage", "https://longest.voyage/"],
["palomakop.tv", "https://palomakop.tv/"],
["2d4.dev", "https://2d4.dev/"],
["nathanwentworth", "https://nathanwentworth.co/"],
["wasin", "https://wasin.io/"],
["inns.studio", "https://inns.studio/"],
["kokorobot.ca", "https://kokorobot.ca/"],
["wake.st", "https://wake.st/"],
["vortok", "https://bildwissenschaft.vortok.info/"],
["aeriform.io", "https://aeriform.io/"],
["nonmateria", "https://nonmateria.com/"],
["drisc", "https://drisc.io/"],
["ricky.codes", "https://ricky.codes/"],
["maxdeviant", "https://maxdeviant.com/"],
["tynandebold", "https://tynandebold.com/"],
["nomand.co", "https://nomand.co/"],
["s-ol.nu", "https://mmm.s-ol.nu/"],
["smidgeo.com/bots", "https://smidgeo.com/bots/"],
["iko.soy", "https://iko.soy/"],
["ritual dust", "https://ritualdust.com/"],
["magoz.is", "https://magoz.is/"],
["szymonkaliski", "https://szymonkaliski.com/"],
["rosano.ca", "https://rosano.ca/"],
["yiming.dev", "https://yiming.dev/"],
["hex22", "https://hex22.org/"],
["patrikarvidsson", "https://patrikarvidsson.com/"],
["sophieleetmaa", "https://sophieleetmaa.com/"],
["xinniw", "https://xinniw.net/"],
["tom hackshaw", "https://tom.so/"],
["madewithtea", "https://www.madewithtea.com/"],
["buzzert.net", "https://buzzert.net/"],
["serocell.com", "https://serocell.com/"],
["kor", "https://kor.nz/"],
["lublin.se", "https://lublin.se/"],
["zanneth", "https://zanneth.com/"],
["eli.li", "https://eli.li/"],
["gosha.net", "https://gosha.net/"],
["azlen.me", "https://azlen.me/"],
["OpGuides", "https://opguides.info/"],
["CMaughan", "https://chrismaughan.com/"],
["oddworlds soliloquy", "https://oddworlds.org/"],
["Fundor333", "https://fundor333.com/"],
["cass.si", "https://cass.si/"],
["mdbenning", "https://mdbenning.neocities.org/"],
["sixey.es", "https://sixey.es/"],
["James Chip", "https://jameschip.io/"],
["patrick-is.cool", "https://patrick-is.cool/"],
["Cr;Lf;", "https://crlf.link/"],
["Jóhannes G. Þorsteinsson", "https://esi.is/"],
["rezmason.net", "https://rezmason.net/"],
["estfyr.net", "https://estfyr.net/"],
["Nat Welch", "https://natwelch.com/"],
["Paul Glushak", "https://0xff.nu/"],
["dreamspace", "https://sunshinegardens.org/~xj9/"],
["q.pfiffer.org", "https://q.pfiffer.org/"],
["zvava", "https://zvava.org/"],
["amorphic.space", "https://amorphic.space/"],
["Archive Fever", "https://www.edwinwenink.xyz/"],
["copiona", "https://copiona.com/"],
["proycon", "https://proycon.anaproy.nl/"],
["roytang.net", "https://roytang.net/"],
["Dampfkraft", "https://dampfkraft.com/"],
["travisshears", "https://travisshears.com/"],
["awalvie", "https://awalvie.me/"],
["futuristan.io", "https://futuristan.io/"],
["yctct", "https://yctct.com/"],
["Felix Elsner", "https://ix5.org/"],
["Julien Desrosiers", "https://www.juliendesrosiers.com/"],
["nchrs.xyz", "https://nchrs.xyz/"],
["Northern Information", "https://nor.the-rn.info/"],
["Matilde Park", "https://matildepark.ca/"],
["deianeira.co", "https://deianeira.co/"],
["inqlab.net", "https://inqlab.net/"],
["abstractxan.xyz", "https://abstractxan.xyz/"],
["m-x marin", "https://mxmarin.ca/"],
["metasyn", "https://metasyn.pw/"],
["milofultz", "https://www.milofultz.com/"],
["Thomasorus", "https://thomasorus.com/"],
["neeasade", "https://notes.neeasade.net/"],
["wesleyac", "https://notebook.wesleyac.com/"],
["wolfm", "https://wol.fm/"],
["automata / vilson vieira", "https://void.cc/"],
["he can jog", "https://hecanjog.com/"],
["fragmentscenario", "https://fragmentscenario.com/"],
["corvid cafe", "https://corvid.cafe/"],
["alessia bellisario", "https://aless.co/"],
["weakty", "https://weakty.com/"],
["mrshll", "https://mrshll.com/"],
["everest pipkin", "https://everest-pipkin.com/"],
["hs0ucy", "https://h.soucy.cc/"],
["Fragments", "https://fragments.hew.tt/"],
["pbatch", "https://pbat.ch/"],
["gr0k", "https://www.gr0k.net/"],
["Clarity Flowers", "https://clarity.flowers/"],
["Ten Digits", "https://tendigits.space/"],
["sirtetris", "https://sirtetris.com/"],
["caffeine", "https://caffeine.wiki/"],
["itwont.work", "https://itwont.work/"],
["badd10de", "https://badd10de.dev/"],
["nilFM", "https://nilfm.cc/"],
["wilde at heart", "https://wilde-at-heart.garden/"],
["pixouls", "https://pixouls.xyz/"],
["embyr.sh", "https://embyr.sh/"],
["maxhaesslein.de", "https://www.maxhaesslein.de/"],
["compudanzas", "https://compudanzas.net/"],
["yhancik", "https://yhnck.xyz/"],
["astral&harr;bijection", "https://astrid.tech/"],
["flower.codes", "https://flower.codes/"],
["noelle.dev", "https://noelle.dev/"],
["giacintocarlucci.it", "https://www.giacintocarlucci.it/"],
["paritybit.ca", "https://www.paritybit.ca/"],
["vlad.website", "https://vlad.website/"],
["Plastic Idolatry", "https://plastic-idolatry.com/erik/"],
["Ferale Art", "https://ferale.art/"],
["toyos.dev", "https://toyos.dev/"],
["Well Observe", "https://www.wellobserve.com/"],
["D00k", "https://d00k.net/"],
["DetonDev", "https://detondev.com/"],
["Aethopica", "https://arcades.agency/"],
["jache.re", "https://jache.re/"],
["Helvetica Blanc", "https://helveticablanc.com/"],
["colindrake.me", "https://colindrake.me/"],
["tone.support", "https://log.tone.support/"],
["armaina", "https://armaina.com/"],
["sindhu.live", "https://sindhu.live/"],
["nuel", "https://nuel.pw/"],
["aphrodite.dev", "https://ffs.fm/"],
["zeal.co", "https://www.aphrodite.dev/"],
["Kaeforest", "https://zeal.co/"],
["canalswans", "https://nataziel.nexus/"],
["Kira's Web - Treehouse", "https://canalswans.commoninternet.net/"],
["chötrin's wiki.", "https://kira.eight45.net/"],
["emile.space.", "https://chotrin.org/"],
["mayaks", "https://emile.space/"],
["vitbaisa", "https://mayaks.eu/"],
["jbztl", "https://vit.baisa.cz/"],
["kxvin", "https://jbztl.fr/"],
["nebula.ed1.club", "https://www.kxvin.com/"],
["plungepool", "https://nebula.ed1.club/stuff/"],
["strickinato", "https://wiki.plungepool.dev/"],
["ghettobastler", "https://aaronstrick.com/"],
["Sweetfish Ayu", "https://ghettobastler.com/"],
["tosatur", "https://ayu.land/"],
["pfych", "https://tosatur.com/"],
["benji", "https://pfy.ch/"],
["manifoldslug", "https://benji.dog/"],
["h3rald", "https://wreckage.link/"],
["louisload", "https://h3rald.com/"],
["monoxane", "https://luis.zip/"],
["lndf", "https://monoxane.io/"],
["ratfactor", "https://lndf.fr/"],
["hideout", "https://ratfactor.com/"],
["Wilbur Zhang", "https://hideout.ink/"],
["Parth Shiralkar", "https://wilburzhang.com/"],
["malloc", "https://parth.ninja/"],
["shrik3", "https://malloc.dog/"],
["Shuang Jiang", "https://shrik3.com/"],
["Zinzy Waleson Geene", "https://jshuang.art/"],
["Matt McAdams", "https://zinzy.website/"],
["Luka Prinčič", "https://mattmcadams.com/"],
["grains.cc", "https://prin.lu/"],
["proto.garden", "https://grains.cc/"],
["kjelsrud.dev", "https://proto.garden/"],
["jaredforth.com", "https://kjelsrud.dev/"],
["Aksui", "https://jaredforth.com/"],
["femishonuga.com", "https://aksui.com/"],
["strengthofone.com", "https://femishonuga.com/"],
["sunil's garden", "https://strengthofone.com/"],
["Zoë Blade's Notebook", "https://garden.sunils.in/"],
["beespace", "https://notebook.zoeblade.com/"],
["jakintosh.com", "https://lunabee.space/extraspace/port.html/"],
["Dziban", "https://jakintosh.com/"],
["Hellien", "https://dziban.net/"],
["slewis.wiki", "https://www.huotart.com/"],
["drawk.cab", "https://www.drawk.cab/"],
["Plantay", "https://plantay.me/"],
["alexeystar.com", "https://alexeystar.com/"],
["22h49", "https://22h49.one/"],
["laeastra", "https://laeastra.com/"],
["ribo.zone", "https://ribo.zone/neighborhood/"],
["visualculture", "https://visualculture.vc/"],
["leetusman.com", "https://leetusman.com/"],
["arne.xyz", "https://arne.xyz/"],
["triapul.cz", "https://triapul.cz/"],
["church basement", "https://churchbasement.org/"],
["sebastian.graphics", "https://sebastian.graphics/"],
["adamledoux.net", "https://adamledoux.net/"],
["comma directory", "https://comma.directory/"],
["meirisoda.online", "https://meirisoda.online/"],
["kelp.lt", "https://kelp.lt/"],
["ewen", "https://ewen.io/"],
["satyarth.me", "https://satyarth.me/"],
["anders.conbere.org", "https://anders.conbere.org/"],
["monolyt.co", "https://monolyt.co/"],
["klaxzy[dot]net", "https://klaxzy.net/"],
["romi grtsk", "https://grtsk.com/"],
["falai.se", "https://falai.se/"],
["sanalog", "https://sanalog.net/blog/"],
["aleteoryx.me", "https://aleteoryx.me/"],
["zewski.net", "https://zewski.net/"],
["drkhsh", "https://drkhsh.at/"],
["ivndbt", "https://ivndbt.com/"],
["Zachary Kai", "https://zacharykai.net/"],
["eevie.dev", "https://eevie.dev/"],
["Andie Keller", "https://bugwhisperer.dev/"],
["akavel", "https://akavel.com/"],
["stage7", "https://stage7.net/"],
["Idiomdrottning", "https://idiomdrottning.org/"],
["thedaemon's space", "https://thedaemons.space/"],
["krzysckh.org", "https://krzysckh.org/"],
["dalem", "https://dalem.foo/"],
["RMV", "https://rmv.fyi/"],
["nnix", "https://nnix.com/"],
["Daryl Sun's Journal", "https://blog.darylsun.page/"],
["Paul Watson", "https://www.lazaruscorporation.co.uk/"],
["tanner", "https://tanner.vc/"],
["lichendust", "https://lichendust.com/"],
["si3t.ch", "https://si3t.ch/"],
["angelwood", "https://angelwood.xyz/"],
["zhcet.net", "https://zhcet.net/"],
["Chris' Place", "https://chris-besch.com/"],
["Ruben Sabatini", "https://rubensabatini.com/"],
["juliannes.website", "https://juliannes.website/"],
["gregori", "https://gregori.studio/"],
["Brennan.Day", "https://brennan.day/"],
["L1Zb3th", "https://l1zb3th.online/"]]